modLoader="javafml"
loaderVersion="[4,)"
license="${mod_license}"
issueTrackerURL=""

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
authors="${mod_author}"
description='''${mod_description}'''
logoFile="assets/${mod_id}/icon.png"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="architectury"
type="required"
versionRange="[${architectury_api_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="owo"
type="required"
versionRange="[${owo_lib_neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jei"
type="optional"
versionRange="[19,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="emi"
type="optional"
versionRange="[1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="roughlyenoughitems"
type="optional"
versionRange="[16,)"
ordering="AFTER"
side="BOTH"
